# Copyright (c) 2023 Anthony Mugendi
# 
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"
sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/rtd_requirements.txt